import { StyleSheet } from "react-native";
import Colors from "./Colors";

const CreatorChooseScreenStyles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: "transparent",
        padding: 16,
    },
    scrollContainer: {
        paddingBottom: 100,
    },
    title: {
        fontSize: 26,
        fontWeight: "700",
        color: Colors.textPrimary,
        marginBottom: 16,
        marginTop: 50,
        textAlign: "center",
    },
    newThemeButton: {
        backgroundColor: Colors.secondary,
        paddingVertical: 14,
        paddingHorizontal: 20,
        borderRadius: 10,
        alignItems: "center",
        marginBottom: 30,
        marginTop: 10,
        shadowColor: Colors.secondary,
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.2,
        shadowRadius: 6,
        elevation: 3,
        alignSelf: "center",
        minWidth: 160,
    },
    newThemeButtonText: {
        color: Colors.background,
        fontSize: 16,
        fontWeight: "600",
        letterSpacing: 0.5,
    },
    themeCard: {
        backgroundColor: Colors.surface,
        borderRadius: 10,
        padding: 16,
        marginBottom: 12,
        borderWidth: 1,
        borderColor: Colors.border,
        shadowColor: Colors.shadowColor,
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.05,
        shadowRadius: 4,
        elevation: 2,
    },
    themeName: {
        fontSize: 18,
        color: Colors.textPrimary,
        marginBottom: 12,
    },
    buttonGroup: {
        flexDirection: "row",
        justifyContent: "space-between",
    },
    button: {
        flex: 1,
        paddingVertical: 10,
        borderRadius: 8,
        alignItems: "center",
        justifyContent: "center",
        marginHorizontal: 5,
        flexDirection: "row",
    },
    buttonRename: {
        backgroundColor: "#D6E4F0",
        shadowColor: "#A3B9D2",
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.15,
        shadowRadius: 3,
        elevation: 2,
    },
    buttonDelete: {
        backgroundColor: "#F8D2D2",
        shadowColor: "#D9A1A1",
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.15,
        shadowRadius: 3,
        elevation: 2,
    },
    textRename: {
        color: "#2F486E",
        fontSize: 14,
        fontWeight: "600",
    },
    textDelete: {
        color: "#B00020",
        fontSize: 14,
        fontWeight: "600",
    },
    emptyText: {
        fontSize: 16,
        color: Colors.textSecondary,
        textAlign: "center",
        marginTop: 40,
    },
    backgroundGrid: {
        position: 'absolute',
        top: 0,
        left: 0,
        right: 0,
        bottom: 0,
        zIndex: -1,
        backgroundColor: Colors.background
    },
    horizontalLine: {
        position: 'absolute',
        left: 0,
        right: 0,
        height: 1,
        backgroundColor: 'rgba(0, 0, 0, 0.04)',
    },
    verticalLine: {
        position: 'absolute',
        top: 0,
        bottom: 0,
        width: 1,
        backgroundColor: 'rgba(0, 0, 0, 0.04)',
    },
});

export default CreatorChooseScreenStyles;