import { StyleSheet } from "react-native";
import Colors from "./Colors";

const styles = StyleSheet.create({
    bg: {
        flex: 1,
        backgroundColor: Colors.background,
        alignItems: "center",
        justifyContent: "center",
        paddingHorizontal: 20,
    },
    title: {
        fontSize: 36,
        fontWeight: "700",
        color: Colors.secondary,
        fontFamily: "monospace",
        textTransform: "uppercase",
        textAlign: "center",
    },
    buttonsRow: {
        flexDirection: "row",
        justifyContent: "space-around",
        width: "100%",
        marginTop: 40,
    },
    button1: {
        backgroundColor: Colors.primary,
        padding: 16,
        borderRadius: 16,
        height: 100,
        width: 150,
        justifyContent: "center",
        alignItems: "center",
        shadowColor: Colors.primary,
        shadowOffset: { width: 0, height: 3 },
        shadowOpacity: 0.3,
        shadowRadius: 5,
        elevation: 6,
    },
    button2: {
        backgroundColor: Colors.secondary,
        padding: 16,
        borderRadius: 16,
        height: 100,
        width: 150,
        justifyContent: "center",
        alignItems: "center",
        shadowColor: Colors.secondary,
        shadowOffset: { width: 0, height: 3 },
        shadowOpacity: 0.3,
        shadowRadius: 5,
        elevation: 6,
    },
    buttonText: {
        color: Colors.background,
        fontSize: 22,
        fontFamily: "monospace",
        fontWeight: "bold",
        textTransform: "uppercase",
    },
    circleTopLeft: {
        position: "absolute",
        top: -60,
        left: -60,
        width: 140,
        height: 140,
        borderRadius: 70,
        backgroundColor: Colors.primary,
        opacity: 0.15,
        zIndex: 1,
    },
    circleBottomRight: {
        position: "absolute",
        bottom: -80,
        right: -80,
        width: 180,
        height: 180,
        borderRadius: 90,
        backgroundColor: Colors.secondary,
        opacity: 0.15,
        zIndex: 1,
    },
    diagonalLine: {
        position: "absolute",
        top: 50,
        left: -50,
        width: 300,
        height: 4,
        backgroundColor: Colors.primary,
        opacity: 0.1,
        transform: [{ rotate: "25deg" }],
        borderRadius: 2,
        zIndex: 1,
    },
    icon: {
        marginBottom: 10,
        zIndex: 10,
    },
});

export default styles;